---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: false
ratings:
  paths:
  - "**.css"
  - "**.js"
exclude_paths:
- lib/
- nls/
- node_modules/
